
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2020-08-11T17:46:05+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "cb06181913f978ea527dd156926ddb75a5929beb",
 "version": "v2.4.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
